// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5RCAcvbkFX2tQbyg5uqr2hKHMDwvxLw',
    appId: '1:408931834087:web:983136e8642f06dfca2a42',
    messagingSenderId: '408931834087',
    projectId: 'qrcode-bloc-459fe',
    authDomain: 'qrcode-bloc-459fe.firebaseapp.com',
    storageBucket: 'qrcode-bloc-459fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6VKsGBHkeFhvBaIXCjbIBlkjOfR2Wmo',
    appId: '1:408931834087:android:311c6e496f69bac3ca2a42',
    messagingSenderId: '408931834087',
    projectId: 'qrcode-bloc-459fe',
    storageBucket: 'qrcode-bloc-459fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2NVONKcRmOuOtKwPcGpxRzBUHcHRshhI',
    appId: '1:408931834087:ios:45fd61bd4488bb7aca2a42',
    messagingSenderId: '408931834087',
    projectId: 'qrcode-bloc-459fe',
    storageBucket: 'qrcode-bloc-459fe.appspot.com',
    iosClientId: '408931834087-7ppnv6ruvl7m9h2erp6eus64o4d5pmme.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2NVONKcRmOuOtKwPcGpxRzBUHcHRshhI',
    appId: '1:408931834087:ios:45fd61bd4488bb7aca2a42',
    messagingSenderId: '408931834087',
    projectId: 'qrcode-bloc-459fe',
    storageBucket: 'qrcode-bloc-459fe.appspot.com',
    iosClientId: '408931834087-7ppnv6ruvl7m9h2erp6eus64o4d5pmme.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrcode',
  );
}
